language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:  
  - pip install -r requirements.txt
  - pip install  coverage
  - pip install coveralls
# command to run tests
script:
  - coverage run -m unittest pycoincap.tests.test_core
  - coverage report -m
after_success:
  - coveralls
